### ISSUE TITLE
Add linux binary

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport-dotnet#1]
Create new nuget `jsreport.Binary.Linux` with linux jsreport binary. This will make the sdk working also on linux.

**Comment by pauldou** [comment]
Do you know where this is in the roadmap?

Thanks

**Comment by pofider** [comment]
There is now beta version available
https://www.nuget.org/packages/jsreport.Binary.Linux/1.8.2-beta1

You can use it the same way as the windows binary. Just make sure you have  `libfontconfig` lib on your linux target. In the default docker your can install it using

```
RUN apt-get update && \   
    apt-get install -y libfontconfig1
```

**Comment by pofider** [comment]
The binary for linux is available.

**Comment by Shadowman4205** [comment]
@pofider 
Hello, in my windows machine the jsreport is working, i am using asp net core.
But when i build docker image with this 

options in DockerFile

FROM microsoft/dotnet:2.1-runtime-stretch-slim

```
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libgdiplus \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && \   
    apt-get install -y libfontconfig1
```

i am getting this error

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.ComponentModel.Win32Exception (8): Exec format error
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at jsreport.Local.Internal.BinaryProcess.InnerExecute(String cmd, Boolean waitForExit)
   at jsreport.Local.Internal.BinaryProcess.ExecuteExe(String cmd, Boolean waitForExit)
   at jsreport.Local.Internal.LocalUtilityReportingService.RenderAsync(String requestString, CancellationToken ct)
```

i installed both nuget package Binary and Binary.Linux

what am i missing?

**Comment by Shadowman4205** [comment]
@pofider 
Yes, i forgot to change this. Thank you very much. 
When jsreport.Binary.Linux vesrion 2 will be available on nuget? 
Cause i am getting "Recipe 'chrome-pdf' not found".

**Comment by Shadowman4205** [comment]
@pofider 
THanks that were the issue. 
But i am getting this error now, is Linux.Binary 2.1.0-beta not working?


> Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
>       An unhandled exception has occurred while executing the request.
> jsreport.Local.JsReportBinaryException: Error rendering report: instance has been daemonized and initialized successfully (pid: 66)A critical error occurred while trying to execute the render command: Failed to launch chrome![1005/151028.862531:WARNING:resource_bundle.cc(358)] locale_file_path.empty() for locale [1005/151028.863962:ERROR:zygote_host_impl_linux.cc(88)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md (1). caused by error (1) -> meta = {"remoteStack":"Error: Failed to launch chrome!\n[1005/151028.862531:WARNING:resource_bundle.cc(358)] locale_file_path.empty() for locale \n[1005/151028.863962:ERROR:zygote_host_impl_linux.cc(88)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n\n    at onClose (jsreportRuntime.js:317739:14)\n    at Interface.helper.addEventListener (jsreportRuntime.js:317728:50)\n    at emitNone (events.js:111:20)\n    at Interface.emit (events.js:208:7)\n    at Interface.close (readline.js:370:8)\n    at Socket.onend (readline.js:149:10)\n    at emitNone (events.js:111:20)\n    at Socket.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}, stack = Error:     at responseToBuffer ([eval]:44323:29)    at concat ([eval]:44376:40)    at ConcatStream.<anonymous> ([eval]:14359:43)    at emitNone (events.js:111:20)    at ConcatStream.emit (events.js:208:7)    at finishMaybe ([eval]:90635:14)    at afterWrite ([eval]:90497:3)    at _combinedTickCallback (internal/process/next_tick.js:144:20)    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by Shadowman4205** [comment]
@pofider 
After search i added these in Dockerfile

```
RUN apt-get update && \
	apt-get install -yyq libappindicator1 libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6
```

And got this error:

> 
> fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
>       An unhandled exception has occurred while executing the request.
> Failed to launch chrome!
> [1005/183004.722514:WARNING:resource_bundle.cc(358)] locale_file_path.empty() for locale
> [1005/183004.724177:ERROR:zygote_host_impl_linux.cc(88)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
> 
> 
> TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
> 
> 2018-10-05 18:30:04 ERR An unhandled exception has occurred while executing the request.
> Failed to launch chrome!
> [1005/183004.722514:WARNING:resource_bundle.cc(358)] locale_file_path.empty() for locale
> [1005/183004.724177:ERROR:zygote_host_impl_linux.cc(88)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
> 
> 
> TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
> 18:30 [Error] [] : An unhandled exception has occurred while executing the request.
> [18:30:04 ERR] An unhandled exception has occurred while executing the request.
> Failed to launch chrome!
> [1005/183004.722514:WARNING:resource_bundle.cc(358)] locale_file_path.empty() for locale
> [1005/183004.724177:ERROR:zygote_host_impl_linux.cc(88)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
> 
> 
> TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

is there example based on linux with v2?

**Comment by mmmagdy3** [comment]
@epozsh did you figure it out **Running as root without --no-sandbox is not supported** problem on linux
