### ISSUE TITLE
ASPNET Core 2.0.3 project with jsreport Nuget packages and Windows Authentication fails to load css and image files

### ISSUE THREAD

**Issue by ksspittctync** [jsreport/jsreport-dotnet#10]
ASPNET Core 2.0.3 project installed with the Nuget packages for jsreport and using the original invoice page provided from jsreport example page.  Using Windows Authentication for the project, errors occur for loading css and image files..
 
I have the following Nuget packages:
Microsoft.AspNetCore.All (2.0.3)
Jsreport.AspNetCore (1.0.1)
Jsreport.Binary (1.9.2)
Jsreport.Local (1.1.0)
I am Running on Windows 10, with VS2017 version 15.4.4,

+0      Starting rendering request 1
+1      Rendering anonymous template { recipe:phantom-pdf,engine:none}
+1      Data item not defined for this template.
+13     Resources not defined for this template.
+14     Base url injected: http://localhost:61443
+15     Rendering engine none
+56     Compiled template not found in the cache, compiling
+59     Replaced images []
+60     Executing recipe phantom-pdf
+788    Converting in dedicated phantomjs 1.9.8
+794    Request file:///C%3A%5CUsers%5Cuser%5CAppData%5CLocal%5CTemp%5Cjsreport%5Cb8d2dd80-d462-11e7-b0ea-b9bb1eb6c727html.html
+795    Request http://localhost:61443/css/invoice.css
+798    Request http://localhost:61443/imgages/logo.png
+826    Unable to load resource (#0URL:http://localhost:61443/imgages/logo.png)
+826    Error code: 5. Description: Operation canceled
+856    Unable to load resource (#0URL:http://localhost:61443/css/invoice.css)
+856    Error code: 5. Description: Operation canceled
+1351   phantom-pdf recipe finished with 1 pages generated
+1352   Skipping storing report.
+1364   Rendering request finished 1

On development workstation, if Anonymous Authentication is turned on, in addition to Windows Authentication, there are no issues.  Attempts to apply permissions on all the wwwroot or application  folders fail to fix issue.  Loading only successful if Anonymous Authentication is activated for web site.  

When deploying to server with IIS, and attempting to apply permissions to web site for Application Pool, Network Service, and Local Service, the issue still occurs.  Only when Anonymous Authentication is applied to the website will the files load correctly.

**Comment by pofider** [comment]
The credentials are not being transferred from .net => jsreport node.js => phantomjs. The final process (phantomjs) doing the requests needs to have an anonymous access to the resources it requires.

One solution is to allow anonymous access for the public resources like styles or images you require.
Another option is to embed inline styles and base64 encode your images.
