### ISSUE TITLE
Error rendering report: instance has been daemonized

### ISSUE THREAD

**Issue by maikolestevez** [jsreport/jsreport-dotnet#11]
Hello, 

I`m trying  to fallow the example that you have in the demos with dotnet core and i`m executing this code on my controller:

```
var rs = new LocalReporting()
                .Configure(cfg => cfg.FileSystemStore())
                .UseBinary(JsReportBinary.GetBinary())
                .AsUtility()
                .Create();


            var report = await rs.RenderByNameAsync("Invoice", new
            {
                number="123",
                seller =new{name="Mayko Estevez",road="La nunnez",country="Dominican Republic" }
                
            });
```
I referenced the studio project to my webproject, and when i call the controller i get this error:

An unhandled exception occurred while processing the request.
JsReportBinaryException: Error rendering report: instance has been daemonized and initialized successfully (pid: 9280)rendering has finished with errors:Error: An error occurred while trying to execute the command: at onCriticalError ([eval]:36106:25) at [eval]:36061:13 at tryCatcher ([eval]:9718:23) at Promise._settlePromiseFromHandler ([eval]:38241:31) at Promise._settlePromise ([eval]:38298:18) at Promise._settlePromise0 ([eval]:38343:10) at Promise._settlePromises ([eval]:38418:18) at Async._drainQueue ([eval]:4650:16) at Async._drainQueues ([eval]:4660:10) at Immediate.Async.drainQueues [as _onImmediate] ([eval]:4534:14) at processImmediate [as _immediateCallback] (timers.js:396:17) {"originalError":{"remoteStack":"Error: Asset Invoice styles.css not found\n at jsreportRuntime.js:123990:15\n at tryCatcher (jsreportRuntime.js:47185:23)\n at Promise._settlePromiseFromHandler (jsreportRuntime.js:129736:31)\n at Promise._settlePromise (jsreportRuntime.js:129793:18)\n at Promise._settlePromise0 (jsreportRuntime.js:129838:10)\n at Promise._settlePromises (jsreportRuntime.js:129917:18)\n at Async._drainQueue (jsreportRuntime.js:42117:16)\n at Async._drainQueues (jsreportRuntime.js:42127:10)\n at Immediate.Async.drainQueues [as _onImmediate] (jsreportRuntime.js:42001:14)\n at processImmediate [as _immediateCallback] (timers.js:396:17)"}}(Original) Error: Error during rendering report: Asset Invoice styles.css not found at [eval]:39138:23 at ConcatStream.<anonymous> ([eval]:44860:43) at emitNone (events.js:72:20) at ConcatStream.emit (events.js:166:7) at finishMaybe ([eval]:4229:14) at afterWrite ([eval]:4115:3) at nextTickCallbackWithManyArgs (node.js:486:18) at process._tickCallback (node.js:384:17) {"remoteStack":"Error: Asset Invoice styles.css not found\n at jsreportRuntime.js:123990:15\n at tryCatcher (jsreportRuntime.js:47185:23)\n at Promise._settlePromiseFromHandler (jsreportRuntime.js:129736:31)\n at Promise._settlePromise (jsreportRuntime.js:129793:18)\n at Promise._settlePromise0 (jsreportRuntime.js:129838:10)\n at Promise._settlePromises (jsreportRuntime.js:129917:18)\n at Async._drainQueue (jsreportRuntime.js:42117:16)\n at Async._drainQueues (jsreportRuntime.js:42127:10)\n at Immediate.Async.drainQueues [as _onImmediate] (jsreportRuntime.js:42001:14)\n at processImmediate [as _immediateCallback] (timers.js:396:17)"}

Any help would be appreciate, thanks

**Comment by pofider** [comment]
The actual error mentions:

> Error: Asset Invoice styles.css not found 

Please check this entity is being copied to the output the same way as the template directory.

**Comment by maikolestevez** [comment]
Thanks, you really help me, now i know how to find  the original error, i was focusing in the exception.

Congratulations for the latest improvement you did, i was using the old versions and now im upgrading, and is much better than before, thanks again to bring such amazing tool for the programmers community.

**Comment by pofider** [comment]
Great. 
Thank you for your support.
Can this be closed now?

**Comment by SaikiSan** [comment]
test
