### ISSUE TITLE
Value passed to the RunInDirectory method not used when running jsreport as local utility

### ISSUE THREAD

**Issue by TheoVan** [jsreport/jsreport-dotnet#12]
Hi,

As posted in the [jsreport forum](https://forum.jsreport.net/topic/379/jsreport-resource-folder-location-when-running-as-utility) the value passed to the RunInDirectory is not used when running jsreport as local utility as opposed to when running as web server.

``` 
public LocalWebReporting AsWebServer()
{
	...

	return new LocalWebReporting(_binary, _cwd, _cfg);
}
public LocalUtilityReporting AsUtility()
{
	...

	return new LocalUtilityReporting(_binary, _cfg);
}  
```

I would really appreciate it if this could be fixed.

**Comment by pofider** [comment]
Thank you for isolating the issue.

This is now fixed in `jsreport.Local 1.1.1`
