### ISSUE TITLE
jsreport is slow

### ISSUE THREAD

**Issue by rajagopal4890** [jsreport/jsreport-dotnet#13]
Hi. I followed the basic configurations that's posted here: [https://jsreport.net/learn/dotnet-local](here).
And my view does not have any cdn. I did go through this blog: [https://jsreport.net/blog/performance-impacting-change-in-v08](blog). However, am confused on where I can put this configuration for my asp net core application. The pdfs take 20 seconds to generate. Any guidance would be of great help. Thanks

**Comment by pofider** [comment]
Can you store your view html and run the pdf printing here? https://playground.jsreport.net
How long it takes there?

**Comment by rajagopal4890** [comment]
Hi @pofider . Thanks for the response. This is my html snippet:
`<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>TestPdf</title>
</head>
<body>
    Hello
</body>
</html>`

I tried in playground. The conversion is instant.

**Comment by pofider** [comment]
Thank you.
Hm. And this takes 20 seconds on your local machine? Or in a shared cloud VM?

Can you try to initialize jsreport like this and try to test pef again?
```cs
var rs = new LocalReporting().UseBinary(JsReportBinary.GetBinary()).AsWebServer().Create();
await rs.StartAsync();
```

**Comment by rajagopal4890** [comment]
@pofider Thanks so much. That indeed helped. Just for the record, please find below my snippet.

```
var rs = new LocalReporting()
                    .UseBinary(JsReportBinary.GetBinary())
                    .AsWebServer()
                    .Create();
            services.AddJsReport(rs);
            rs.StartAsync();
```
