### ISSUE TITLE
.Net Core Web App Publish in Ubuntu

### ISSUE THREAD

**Issue by fsfj** [jsreport/jsreport-dotnet#15]
I got an error in printing pdf if my app is publish. If not, web app successfully printed pdf.

I put this on my Startup.cs:

services.AddJsReport(new LocalReporting().UseBinary(jsreport.Binary.Linux.JsReportBinary.GetBinary()).AsUtility().Create());

**Comment by pofider** [comment]
Only pdf is not being print? The html recipe works?
Can you try to run this on the target machine?
```
apt-get install -y libfontconfig1
```

**Comment by fsfj** [comment]
I'm not using html recipe, only phantom pdf recipe. It's okay in development. but not worked in production.

I already installed that Sir, but no luck.

Thank you

**Comment by pofider** [comment]
Please try also the html recipe so we can limit the area where to search for the problem.
Can you dump the exception which you see and paste it here? It contains jsreport output log.

**Comment by fsfj** [comment]
I've also tried the html recipe, not working. I can't find the jsreport output log.

This is my publish file:
The jsreport folder has no file/output log inside.
![image](https://user-images.githubusercontent.com/11935862/36472537-15f65732-172d-11e8-84fd-016f201799a5.png)

**Comment by pofider** [comment]
Ok. Thanks for trying html recipe.
At what point it crashes for you? What is the exception? Please share the part of the code where it crashes.

**Comment by fsfj** [comment]
I don't know where it crashes coz i encounter the error in production, not in development. It works in development.

**Comment by fsfj** [comment]
![image](https://user-images.githubusercontent.com/11935862/36480184-55d6047e-1746-11e8-9840-d5b256a76167.png)

I encounter this now

**Comment by pofider** [comment]
Did you try to add permissions to the /tmp folder for the running process?

**Comment by fsfj** [comment]
This is the permission for autocleanup:
![image](https://user-images.githubusercontent.com/11935862/36517034-a7adf688-17bb-11e8-962c-e55e383787f9.png)

This is the permission for tmp:
![image](https://user-images.githubusercontent.com/11935862/36517076-d8c83eea-17bb-11e8-898e-9ebf87e88857.png)

**Comment by fsfj** [comment]
Hello @pofider , 

Phantom pdf recipe now works in production. I just run this command:
sudo apt-get dist-upgrade

But the size of the font is different in my windows (development platform) to ubuntu server (production platform)

Windows:

![image](https://user-images.githubusercontent.com/11935862/36522015-0210bf16-17d5-11e8-857e-fe8bd0dd2c9b.png)

Ubuntu Server:

![image](https://user-images.githubusercontent.com/11935862/36522025-13102bc6-17d5-11e8-894e-3a56ad25c73f.png)

**Comment by bjrmatos** [comment]
hi @fsfj, the size differences between Linux and Windows is expected, take a look at [this](https://jsreport.net/learn/phantom-pdf#different-sizes-on-windows-vs-unix) for some workaround.

**Comment by pofider** [comment]
Closing as the main issue is solved here.
