### ISSUE TITLE
Rendering JSReport as partial view in ASP.NET MVC throws HttpException: Filtering is not allowed

### ISSUE THREAD

**Issue by skendrot** [jsreport/jsreport-dotnet#16]
I want to render a JSReport as a partial view of my MVC Razor page. The page would show some information, and then have a section where the PDF would show. Rendering partial views with controllers is usually done with the RenderAction method. This is failing when calling a method that generates a PDF

Razor example:
```
    <div>
        <table>
            <~-- Some more content -->
        </table>
    </div>
    <div>
        @{Html.RenderAction("PdfAction", "Home"); }
    </div>
```

Controller:
```
        // Below attribute limits the action to only requests from other actions, cannot directly link to it
        //[ChildActionOnly]
        [EnableJsReport()]
        public ActionResult PdfAction()
        {
            HttpContext.JsReportFeature().Recipe(Recipe.PhantomPdf);

            // both calls fail
            return PartialView(InvoiceModel.Example());
            //return View(InvoiceModel.Example());
        }
```

When trying to render it throws a HttpException with message "Filtering is not allowed."

**Comment by pofider** [comment]
Hm. Doesn't this mean that you try to put a pdf into html?

```cs
 <div>
        <table>
            <~-- Some more content -->
        </table>
    </div>
    <div>
        @{Html.RenderAction("PdfAction", "Home"); }
    </div>
```

Regardless the mentioned error, this won't work. I believe you have to do an additional async request or a sync post to an iframe.

**Comment by pofider** [comment]
A lot has changed in the jsreport v3 sdk, please test it there and come back if you have still troubles.
