### ISSUE TITLE
Serializing RenderRequest.Data should not change props casing

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport-dotnet#17]
More details
https://forum.jsreport.net/topic/494/bug-net-issue-with-case-in-data-object-pssed-to-renderbynameasync

**Comment by pofider** [comment]
Solved in v2

**Comment by dmehrtens66** [comment]
I am using version 3.0.1 of Client, 2.1.0 for Shared, and 2.7.0 for types.  My data object properties are getting camel cased.

**Comment by pofider** [comment]
@dmehrtens66 I was living in a false reality that this has been fixed.  I apologize for the problem. I've now released jsreport.Shared@2.2.0 with fix. Please let me know if it works for you.
