### ISSUE TITLE
Using 3rd party extensions

### ISSUE THREAD

**Issue by HEBOS** [jsreport/jsreport-dotnet#18]
Hi,

Is there any way to include any 3rd party library, such as  formatJs.
I'm designing reports using local JsReport studio using feature ".AsWebServer()".

Thanks

**Comment by bjrmatos** [comment]
hi! have you tried to follow [these instructions](https://jsreport.net/learn/dotnet-local#custom-extensions)?

**Comment by pofider** [comment]
This should work. Can you make sure you have in the external modules got properly installed to `jsreport/node_modules/handlebars-intl` ?
It would help if you create a minimal repository (without your unrelated code) we can try to analyse.

**Comment by HEBOS** [comment]
Hi @pofider ,

I've attached a sample project. Note that I have two project. One is used for design time, and one for run time. Report folder is saved in run-time project (ReportServer), and design-time project (ReportDesigner) is used by developers only, otherwise they are similar.

Try to run this template:
[http://localhost:55555/studio/templates/BJYoCEqnf](http://localhost:55555/studio/templates/BJYoCEqnf)

Code that does not execute is in "global helpers.js", e.g. [http://localhost:55555/studio/assets/SkMw3X69l](http://localhost:55555/studio/assets/SkMw3X69l)

[SampleProject.zip](https://github.com/jsreport/jsreport-dotnet/files/1952613/SampleProject.zip)

Thank you

**Comment by pofider** [comment]
Thank you.
I can replicate your issue, I will try to investigate what could be the problem in the next days.

**Comment by pofider** [comment]
Hm. It seems the `handlebars-intl` requires [Intl](https://nodejs.org/api/intl.html) but our compiled node.js version doesn't have it.  The real error is unfortunately hidden and you can get it if you try/catch handlebars-intl/index and write the error to file...

I've submitted task [here](https://github.com/jsreport/jsreport-cli/issues/15) to investigate why our compilation of nodejs excludes Int. However this will take some time.

I would recommend to find an alternative to the handlebars-intl that doesn't require browser support for Intl and does the work manually.

**Comment by lucipacurar** [comment]
I'm having the same problem: I cannot load `momentjs` for example.

I have the following `jsreport.config.json`: 
```
{
    "discover": true,
    "allowLocalFilesAccess": true,
    "templatingEngines": {
        "allowedModules": "*"
    },
    "store": { "provider": "fs" },
  "extensions": {
    "comment": "helpers and scripts are different...",
    "tasks": { "allowedModules": "*" },
    "scripts": { "allowedModules": "*" },
    "assets": {
      "allowedFiles": "static/**/*.*",
      "searchOnDiskIfNotFoundInStore": true,
      "rootUrlForLinks": "https://mywebsite",
      "publicAccessEnabled": false
    }
  },
  "scripts": {
    "allowedModules": [ "*" ]
  }
}
```

and I get the following error: 

```
Unhandled Exception: jsreport.Client.JsReportException: Unable to render template.  Error while executing user script. Unable to find module node_modules/moment/moment.js
Searched paths:
node_modules/moment/moment.js
C:\Projects\ConsoleApp3\reports\node_modules\moment\moment.js
C:\Projects\ConsoleApp3\reports\node_modules\moment\moment.js
C:\Projects\ConsoleApp3\reports\node_modules\moment\moment.js
.
```

The file is located here: `C:\Projects\ConsoleApp3\reports\node_modules\moment\moment.js`

**Comment by Dafrapster** [comment]
I am running into this as well. Is there any update on this issue? This ticket has been open for 7 months and leaves helpers almost entirely unusable on dotnet platforms.

**Comment by pofider** [comment]
I apologize for the late response here.
The custom helpers from npm should work. 
I have tested it with the latest jsreport.Binary.
It is also documented now - https://jsreport.net/learn/dotnet-local#custom-npm-helpers

The handlebars-intl unfortunately won't work because its dependency on some native features that are not build in, so you need to use a different package. It is also documented and we have extra issue for it [here](https://github.com/jsreport/jsreport-cli/issues/15).

Closing. The 3rd party modules should work. Feel free to comment or create new issue if you have still problems on the latest version.
