### ISSUE TITLE
JSReport don't load image in asp net core project

### ISSUE THREAD

**Issue by mindior** [jsreport/jsreport-dotnet#19]
I'm using jsreport to convert an html page to pdf in asp net core. When I display the page in html format the image appears. When I convert to pdf the image is not shown. The pdf prints all the properties of the template, except for the image. I tried to use a header and the same thing happens.

**Comment by pofider** [comment]
Perhaps this is fixed for you in v2.
Please reopen if not.

**Comment by sudhir2311** [comment]
> I'm using jsreport to convert an html page to pdf in asp net core. When I display the page in html format the image appears. When I convert to pdf the image is not shown. The pdf prints all the properties of the template, except for the image. I tried to use a header and the same thing happens.

Having same issue in JSReport. JSReport is Third class library to generate report
