### ISSUE TITLE
Add osx binary

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport-dotnet#2]
Create new nuget `jsreport.Binary.OSX` with osx jsreport binary. This will make the sdk working also on mac.

**Comment by IgorMoreira** [comment]
Do you have an expected date for this?

**Comment by pofider** [comment]
I've just released the [jsreport.Binary.OSX](https://www.nuget.org/packages/jsreport.Binary.OSX/1.8.2-beta1) in pre-release. Would you be able to try it out?

Note that the `phantom-pdf` recipe won't work there if you use OSX Sierra, because the default jsreport uses `phantomjs 1.9` which is not supported there. I will need to release also version with the `phantomjs 2` for it.

**Comment by pofider** [comment]
The binary for osx is available.
