### ISSUE TITLE
jsreport v2 binaries and chrome

### ISSUE THREAD

**Issue by justin-dx** [jsreport/jsreport-dotnet#21]
I'm trying to generate a pdf that contains an image (from a local directory) and hyperlinks in the content. Using _jsreport.Binary_ allows the images to work, but the links break, while _jsreport.Binary.Ph2_ allows the links to work, but breaks the images.
This is a problem inherent with PhantomJS - the latest version of jsReport now uses Chrome by default for these reasons (among others).
Are there plans to release the latest .net wrappers/binaries in the pipeline?

**Comment by pofider** [comment]
Yes, we have it in the pipeline.  There are just too many things to update after the v2 release...

I think I could ship at least the beta versions of nuget packages this week.

**Comment by pofider** [comment]
The pre-release nugets are availible and include chrome recipe by default. Please give it a try.

**Comment by fabich** [comment]
> The pre-release nugets are availible and include chrome recipe by default. Please give it a try.
@pofider 

Do I need to install chrome-pdf via npm?
(jsreport.config.json => "discover": true)

I'm always receiving an error:
``` JsReportBinaryException: Error rendering report: instance has been daemonized and initialized successfully (pid: 23756)rendering has finished with errors:Error: An error occurred while trying to execute the command: at onCriticalError ([eval]:29603:25) at [eval]:29558:13 at tryCatcher ([eval]:36038:23) at Promise._settlePromiseFromHandler ([eval]:34061:31) at Promise._settlePromise ([eval]:34118:18) at Promise._settlePromise0 ([eval]:34163:10) at Promise._settlePromises ([eval]:34238:18) at Async._drainQueue ([eval]:31008:16) at Async._drainQueues ([eval]:31018:10) at Immediate.Async.drainQueues [as _onImmediate] ([eval]:30892:14) at processImmediate [as _immediateCallback] (timers.js:396:17) {"originalError":{"remoteStack":"Error: Recipe 'chrome-pdf' not found\n at jsreportRuntime.js:138917:13\n at tryCatcher (jsreportRuntime.js:47277:23)\n at Promise._settlePromiseFromHandler (jsreportRuntime.js:45299:31)\n at Promise._settlePromise (jsreportRuntime.js:45356:18)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at Promise._resolveCallback (jsreportRuntime.js:45219:57)\n at Promise._settlePromiseFromHandler (jsreportRuntime.js:45311:17)\n at Promise._settlePromise (jsreportRuntime.js:45356:18)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at PromiseArray._resolve (jsreportRuntime.js:45690:19)\n at PromiseArray._promiseFulfilled (jsreportRuntime.js:45708:14)\n at Promise._settlePromise (jsreportRuntime.js:45361:26)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at Promise._settlePromise (jsreportRuntime.js:45369:21)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at Promise._resolveCallback (jsreportRuntime.js:45241:14)\n at Promise._settlePromiseFromHandler (jsreportRuntime.js:45311:17)\n at Promise._settlePromise (jsreportRuntime.js:45356:18)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at Promise._resolveCallback (jsreportRuntime.js:45219:57)\n at Promise._settlePromiseFromHandler (jsreportRuntime.js:45311:17)\n at Promise._settlePromise (jsreportRuntime.js:45356:18)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at Promise._resolveCallback (jsreportRuntime.js:45219:57)\n at Promise._settlePromiseFromHandler (jsreportRuntime.js:45311:17)\n at Promise._settlePromise (jsreportRuntime.js:45356:18)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at jsreportRuntime.js:44716:21\n at nextTickCallbackWith0Args (node.js:442:9)\n at process._tickCallback (node.js:371:13)"}}(Original) Error: Error during rendering report: Recipe 'chrome-pdf' not found at [eval]:36644:23 at ConcatStream.<anonymous> ([eval]:42366:43) at emitNone (events.js:72:20) at ConcatStream.emit (events.js:166:7) at finishMaybe ([eval]:4229:14) at afterWrite ([eval]:4115:3) at nextTickCallbackWithManyArgs (node.js:486:18) at process._tickCallback (node.js:384:17) {"remoteStack":"Error: Recipe 'chrome-pdf' not found\n at jsreportRuntime.js:138917:13\n at tryCatcher (jsreportRuntime.js:47277:23)\n at Promise._settlePromiseFromHandler (jsreportRuntime.js:45299:31)\n at Promise._settlePromise (jsreportRuntime.js:45356:18)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at Promise._resolveCallback (jsreportRuntime.js:45219:57)\n at Promise._settlePromiseFromHandler (jsreportRuntime.js:45311:17)\n at Promise._settlePromise (jsreportRuntime.js:45356:18)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at PromiseArray._resolve (jsreportRuntime.js:45690:19)\n at PromiseArray._promiseFulfilled (jsreportRuntime.js:45708:14)\n at Promise._settlePromise (jsreportRuntime.js:45361:26)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at Promise._settlePromise (jsreportRuntime.js:45369:21)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at Promise._resolveCallback (jsreportRuntime.js:45241:14)\n at Promise._settlePromiseFromHandler (jsreportRuntime.js:45311:17)\n at Promise._settlePromise (jsreportRuntime.js:45356:18)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at Promise._resolveCallback (jsreportRuntime.js:45219:57)\n at Promise._settlePromiseFromHandler (jsreportRuntime.js:45311:17)\n at Promise._settlePromise (jsreportRuntime.js:45356:18)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at Promise._resolveCallback (jsreportRuntime.js:45219:57)\n at Promise._settlePromiseFromHandler (jsreportRuntime.js:45311:17)\n at Promise._settlePromise (jsreportRuntime.js:45356:18)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at jsreportRuntime.js:44716:21\n at nextTickCallbackWith0Args (node.js:442:9)\n at process._tickCallback (node.js:371:13)"}```

**Comment by justin-dx** [comment]
If you're using the .net core wrapper, you'll need the updated binary, types and local nuget packages.
