### ISSUE TITLE
jsreport v2 binaries with chrome on Azure App Service

### ISSUE THREAD

**Issue by fabich** [jsreport/jsreport-dotnet#22]
Hi

Should it be possible to run the new jsreport v2 binaries with chrome on Azure App Services?

Thanks for your help!

**Comment by fabich** [comment]
So I guess the problem is the same as running jsreport with chrome using nodejs

`018-07-03 16:20:25.553 +00:00 [Error] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HLF0VQBMG5AV", Request id "0HLF0VQBMG5AV:00000004": An unhandled exception was thrown by the application.
jsreport.Local.JsReportBinaryException: Error rendering report: A critical error occurred while trying to execute the render command: spawn UNKNOWN (1). caused by error (1) -> meta = {"remoteStack":"Error: spawn UNKNOWN\n    at _errnoException (util.js:1022:11)\n    at ChildProcess.spawn (internal/child_process.js:323:11)\n    at Object.exports.spawn (child_process.js:503:9)\n    at Function.launch (jsreportRuntime.js:317426:40)\n    at <anonymous>"}, stack = Error:     at responseToBuffer ([eval]:44291:29)    at concat ([eval]:44344:40)    at ConcatStream.<anonymous> ([eval]:14359:43)    at emitNone (events.js:111:20)    at ConcatStream.emit (events.js:208:7)    at finishMaybe ([eval]:90572:14)    at afterWrite ([eval]:90434:3)    at _combinedTickCallback (internal/process/next_tick.js:144:20)    at process._tickCallback (internal/process/next_tick.js:180:9)
`

@pofider Could you publish the Linux binary v2 as beta as well so I can try running it on an App Service on Linux?

**Comment by penihel** [comment]
I had the same problem now.

@pofider can you help us?

**Comment by penihel** [comment]
unfortunately, i suspect that the problem is this
**https://github.com/GoogleChrome/puppeteer/issues/515**

**Comment by penihel** [comment]
Hi @fabich 
I dont think that is..
I Have a Windows Based Azure App Service running jsreport with phantonJS (nuget jsreport.Binary version 1.10). And Works fine.
There is just a limitation about de App Service Plan.  See this https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#unsupported-frameworks
The Service plan must to be "Basic " or higher

**Comment by fabich** [comment]
@penihel I was talking about running jsreport with chrome-pdf

**Comment by pofider** [comment]
Unfortunately, I am afraid that chrome won't work in restricted environment like azure web app.
I didn't get to try it out, but looking on internet it seems puppeteer doesn't work there - https://github.com/GoogleChrome/puppeteer/issues/515

You can run jsreport official docker image in azure web app and connect to it from your .net app. 
Or create your own image together with your .net app.

,

**Comment by fabich** [comment]
@pofider is chrome-pdf available on jsreport online?

**Comment by pofider** [comment]
We are currently working on updating jsreportonline to the latest version including chrome, version control... It can take 1 - 3 weeks.
Until then there is electron recipe which also renders using chrome on behind.

**Comment by penihel** [comment]
I believe we have a solution without "docker". Because this is an awful lot for jsreport. This will take away most developers, discouraging them from using jsreport

**Comment by fabich** [comment]
@penihel I don't think so, it's actually very easy with the new [Azure Web App for Containers](https://azure.microsoft.com/en-us/services/app-service/containers/).
Just use the docker image provided by the jsreport team:
[jsreport/jsreport:latest-full](https://hub.docker.com/r/jsreport/jsreport/)

I'm closing this issue now.
Our solution: don't include jsreport in the .net core app if you want to use chrome-pdf.
Only use the jsreport.Client v3.0.0+ and send the request to a jsreport docker container.

**Comment by penihel** [comment]
In this case I'd rather give up using jsreport and use only the
https://github.com/rdvojmoc/DinkToPdf (wkhtmltopdf)

That allows me to use only one App Service on azure. No need to use docker

**Comment by rafaelramosdf** [comment]
> In this case I'd rather give up using jsreport and use instead this lib
> https://github.com/rdvojmoc/DinkToPdf (wkhtmltopdf)
> 
> That allows me to use only one App Service on azure. No need to use docker

Very good, thanks for the tip @penihel 👍 :D
