### ISSUE TITLE
LocalReporting Jsreport  azure Web App

### ISSUE THREAD

**Issue by vidya091209** [jsreport/jsreport-dotnet#28]
I am hosting a .net core app in azure web app.
 services.AddJsReport(new LocalReporting().UseBinary(JsReportBinary.GetBinary()).AsUtility().Create());
             HttpContext.JsReportFeature().Recipe(Recipe.ChromePdf,)
                .OnAfterRender((r) => HttpContext.Response.Headers["Content-Disposition"] =filename);
          i want to download the report. locally it works but from web app it just render as html report.

**Comment by pofider** [comment]
Please share the full code of the controller method.

**Comment by vidya091209** [comment]
[MiddlewareFilter(typeof(JsReportPipeline))]
        public async Task<IActionResult> Download(string id, string status, string type="PDF")
        {
            ViewBag.Status = status;
            
            var filename=$"attachment; filename=\"Customer List_{DateTime.Now.ToString("MM-dd-yy-HH-MM-ss") }.pdf\"";
            HttpContext.JsReportFeature().Recipe(Recipe.ChromePdf)
                .OnAfterRender((r) => HttpContext.Response.Headers["Content-Disposition"] =filename);
            return View("Customer", await _customerService.GetCustomerSearchAsync(new ViewModel.CustomerFilter() { CustomerTypeId=id }));
        }

**Comment by pofider** [comment]
Hm, this looks good.
I don't see any reason why it should return something different in azure web app.
Do you get this problem just in this particular case or is it general?

**Comment by vidya091209** [comment]
is there any limitation in using azure web app. i have seen there was a issue reported for the same.

**Comment by vidya091209** [comment]
this means at minimum  i have  to have linux container running

**Comment by pofider** [comment]
Yes.
However the chrome should just fail on windows. It is strange that it is returning html for you.

**Comment by vidya091209** [comment]
Hi I have modified my docker file as FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443
RUN apt-get update && \   
    apt-get install -y gnupg  libgconf-2-4 wget && \
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
    apt-get update && \
    apt-get install -y google-chrome-unstable --no-install-recommends

ENV chrome:launchOptions:args --no-sandbox

The main issue i am facing is adding  nuget package
 **<PackageReference Include="jsreport.Binary.Linux" Version="2.3.0" />**
it is taking more than 3 hours  to download but even after that it is getting timeout.

**Comment by vidya091209** [comment]
nuget package  Include="jsreport.Binary.Linux"

**Comment by vidya091209** [comment]
thanks. it is working. but performance wise it is too slow. for 57KB report it is taking more than 1 minute.

**Comment by pofider** [comment]
The rendering should be slow just the first time. Isn't it?

You can try to use this "AsWebServer" switch
https://jsreport.net/learn/dotnet-local#utility-or-web-server
which can speed it up a bit.

What azure plan do you use? How is the performance on your local?

**Comment by vidya091209** [comment]
Its Standard S1. locally it is a faster.

**Comment by vidya091209** [comment]
but you recommend to use "It is generally recommended to use the utility based strategy in production"

**Comment by vidya091209** [comment]
one the same instance i also wanted to support to download excel. this my local running code but in docker it is showing as inline 

  **HttpContext.JsReportFeature()
                   // the normal jsreport base url injection into the html doesn't work properly with docker and asp.net because of port mapping
                   // the project typically starts with some http://localhost:1234 url but inside docker the url is http://localhost
                   .Configure((req) => {
                       req.Options.Base = "http://localhost";
                       req.Template.HtmlToXlsx = new HtmlToXlsx() { HtmlEngine = "chrome" };
                   })
                   .Recipe(Recipe.HtmlToXlsx);**

**Comment by vidya091209** [comment]
No excel report is rendering as html.
please update the sample code https://github.com/jsreport/jsreport-dotnet-example-docker
to support excel  download. thanks.

**Comment by pofider** [comment]
You can also consider using [jsreportonline(https://jsreport.net/online) instead of the `jsreport.Local`. It is in many situations more effective for maintenance and resources cost. Just giving you options...

**Comment by pofider** [comment]
I added the excel example, but there is nothing interesting. Check it out.

**Comment by vidya091209** [comment]
<img width="421" alt="capture" src="https://user-images.githubusercontent.com/12954559/50967474-41d15f80-14fe-11e9-8822-c4139a3d1ec1.PNG">

this is how my report is looking right now instead of getting downloaded.

and we don't need this right?
 .OnAfterRender((r) => HttpContext.Response.Headers["Content-Disposition"] = filename);

**Comment by pofider** [comment]
> and we don't need this right?

No it should not be needed.

It must be something with your setup, I don't know. Try to compare it with my example and find out what is different. Or share a simple sample repo for me so I can take a look.

**Comment by pofider** [comment]
A lot has changed in the jsreport v3 sdk, please test it there and come back if you have still troubles.
