### ISSUE TITLE
Add chrome-image support

### ISSUE THREAD

**Issue by mchristensen80** [jsreport/jsreport-dotnet#31]
It looks like a chrome-png recipe is being added to jsreport.

https://github.com/jsreport/jsreport-chrome-pdf
https://github.com/jsreport/jsreport/issues/478

Are there any plans to add support to the dotnet sdk?

**Comment by pofider** [comment]
You can now update deps - mainly jsreport.Types@2.4.0 and jsreport.Binary@2.4.0 to have support for `chrome-image` in .net.

**Comment by mchristensen80** [comment]
Thank you!
