### ISSUE TITLE
(Recipe 'chrome-pdf' not found) error, when upload the website to IIS

### ISSUE THREAD

**Issue by khaledsale7** [jsreport/jsreport-dotnet#32]
JSreport is working well in my local asp mvc application, but when i move it to IIS server it show an error message that chrome-pdf not found

Log:

10/03/2019 14:45:50 ==> Error rendering report: instance has been daemonized and initialized successfully (pid: 8416)rendering has finished with errors:Error: An error occurred while trying to execute the command:    at onCriticalError ([eval]:36086:25)    at [eval]:36041:13    at tryCatcher ([eval]:9718:23)    at Promise._settlePromiseFromHandler ([eval]:38221:31)    at Promise._settlePromise ([eval]:38278:18)    at Promise._settlePromise0 ([eval]:38323:10)    at Promise._settlePromises ([eval]:38398:18)    at Async._drainQueue ([eval]:4650:16)    at Async._drainQueues ([eval]:4660:10)    at Immediate.Async.drainQueues [as _onImmediate] ([eval]:4534:14)    at processImmediate [as _immediateCallback] (timers.js:396:17) {"originalError":{"remoteStack":"Error: Recipe 'chrome-pdf' not found\n    at jsreportRuntime.js:124986:13\n    at tryCatcher (jsreportRuntime.js:127974:23)\n    at Promise._settlePromiseFromHandler (jsreportRuntime.js:127667:31)\n    at Promise._settlePromise (jsreportRuntime.js:127724:18)\n    at Promise._settlePromise0 (jsreportRuntime.js:127769:10)\n    at Promise._settlePromises (jsreportRuntime.js:127848:18)\n    at Async._drainQueue (jsreportRuntime.js:41399:16)\n    at Async._drainQueues (jsreportRuntime.js:41409:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (jsreportRuntime.js:41283:14)\n    at processImmediate [as _immediateCallback] (timers.js:396:17)"}}(Original) **Error: Error during rendering report: Recipe 'chrome-pdf' not found**    at [eval]:39083:23    at ConcatStream.<anonymous> ([eval]:44805:43)    at emitNone (events.js:72:20)    at ConcatStream.emit (events.js:166:7)    at finishMaybe ([eval]:4229:14)    at afterWrite ([eval]:4115:3)    at nextTickCallbackWithManyArgs (node.js:486:18)    at process._tickCallback (node.js:384:17) {"remoteStack":"Error: Recipe 'chrome-pdf' not found\n    at jsreportRuntime.js:124986:13\n    at tryCatcher (jsreportRuntime.js:127974:23)\n    at Promise._settlePromiseFromHandler (jsreportRuntime.js:127667:31)\n    at Promise._settlePromise (jsreportRuntime.js:127724:18)\n    at Promise._settlePromise0 (jsreportRuntime.js:127769:10)\n    at Promise._settlePromises (jsreportRuntime.js:127848:18)\n    at Async._drainQueue (jsreportRuntime.js:41399:16)\n    at Async._drainQueues (jsreportRuntime.js:41409:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (jsreportRuntime.js:41283:14)\n    at processImmediate [as _immediateCallback] (timers.js:396:17)"}
10/03/2019 14:45:51 ==> Controller: Error Action: ErrorA potentially dangerous Request.QueryString value was detected from the client (message="...catStream.<anonymous> ([eval]:..."). && A potentially dangerous Request.QueryString value was detected from the client (message="...catStream.<anonymous> ([eval]:...").

**Comment by pofider** [comment]
You seems to use some kind of very old project and nuget `jsreport.Embedded` which is deprecated for very long time and new nugets `jsreport.Local`.... 

The `jsreport` folder you show on the screenshot shouldn't be there at all in this form. It was created `jsreport.Embedded`. You should probably deleted or even better start from scratch. See the .net example repository. Do you get the same error there?
https://github.com/jsreport/jsreport-dotnet-example-net-webapp

**Comment by khaledsale7** [comment]
> 
> 
> You seems to use some kind of very old project and nuget `jsreport.Embedded` which is deprecated for very long time and new nugets `jsreport.Local`....
> 
> The `jsreport` folder you show on the screenshot shouldn't be there at all in this form. It was created by`jsreport.Embedded`. You should probably delete or even better start from scratch. See the .net example repository. Do you get the same error there?
> https://github.com/jsreport/jsreport-dotnet-example-net-webapp

Hello again dear jan
Thank you for your reply, appreciate this ☺

I have uploaded the example project from the link to the IIS server, and it works fine, but in my project it doesn't, where i have the same versions of NuGet as in the example project.

Waiting for your help and response.
best regards.

**Comment by khaledsale7** [comment]
any help ?

**Comment by pofider** [comment]
Please try to kill node.js processes and run it again.
If it doesn't help, please share a repository so I can take a look at what is wrong.

**Comment by pofider** [comment]
A lot has changed in the jsreport v3 sdk, please test it there and come back if you have still troubles.
