### ISSUE TITLE
JsReportBinaryException: Error rendering report:

### ISSUE THREAD

**Issue by huxaiphaer** [jsreport/jsreport-dotnet#35]
Am using a mac to develop a .net core web app, but I found out that its an issue with a mac, but on windows, it works fine.
How can I resolve this?

Below is the full error log

> JsReportBinaryException: Error rendering report:
> jsreport.Local.Internal.LocalUtilityReportingService+<RenderAsync>d__10.MoveNext()
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> jsreport.AspNetCore.JsReportMiddleware+<Invoke>d__3.MoveNext()
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext()
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext()
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()
> 

<img width="1099" alt="Screenshot 2019-07-19 at 00 50 55" src="https://user-images.githubusercontent.com/14312249/61494647-63386a00-a9bf-11e9-94b9-d5618737c247.png">

**Comment by bjrmatos** [comment]
@huxaiphaer i guess this was solved also by the change mentioned [here](https://github.com/jsreport/jsreport-dotnet-example-webapp/issues/5#issuecomment-513762744), right? closing it, but if it is not solved let me know

**Comment by pofider** [comment]
Duplicate
https://github.com/jsreport/jsreport-dotnet-example-webapp/issues/5
