### ISSUE TITLE
Failed to parse parameter value: 29,70389cm  jsreportRuntime.js

### ISSUE THREAD

**Issue by vihorlat** [jsreport/jsreport-dotnet#36]
Hello,
we use jsreport to generate a pdf. It works fine, but on one machine we are getting this error:

`  Error rendering report: A critical error occurred while trying to execute the render command: Failed to parse parameter value: 29,70389cm (1). caused by error (1) -> meta = {"remoteStack":"Error: Failed to parse parameter value: 29,70389cm\n    at assert (jsreportRuntime.js:418725:11)\n    at convertPrintParameterToInches (jsreportRuntime.js:417421:5)\n    at Page.pdf (jsreportRuntime.js:417161:20)\n    at Page.<anonymous> (jsreportRuntime.js:418605:23)\n    at runWithTimeout (jsreportRuntime.js:161246:27)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}, stack = Error:     at responseToBuffer ([eval]:68314:29)    at concat ([eval]:68367:40)    at ConcatStream.<anonymous> ([eval]:11565:43)    at emitNone (events.js:111:20)    at ConcatStream.emit (events.js:208:7)    at finishMaybe ([eval]:100191:14)    at afterWrite ([eval]:100053:3)    at _combinedTickCallback (internal/process/next_tick.js:144:20)    at process._tickCallback (internal/process/next_tick.js:180:9)    at jsreport.Local.Internal.LocalUtilityReportingService.RenderAsync(String requestString, CancellationToken ct)
   at Services.PDFGeneratorService.GenerateProductionDrawing(String sourcePdfFilePath, String outputPdfsourcePdfFilePath, ProductionDrawingViewModel model, String viewName) in D:\work\server\Services\PDFGeneratorService.cs:line 117
   at Services.PrintService.GenerateProductionDrawingPDF(ProductionDrawingViewModel productionDrawingViewModel) in D:\work\server\Services\PrintService.cs:line 270
   at Services.PrintService.PrintProductionDrawingAsync(ProductionPlanPrint productionPlanPrint) in D:\work\server\Services\PrintService.cs:line 142`

I guess the problem is with decimal separator. 
What do you suggest please ?

Thank you very much

**Comment by pofider** [comment]
I think you have different locale on that failing machine. The easiest is probably to match the windows locale.

Or you can probably do it also in c#
```
System.Threading.Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo("en-US")
```

**Comment by vihorlat** [comment]
Thank you, the windows setting worked.
