### ISSUE TITLE
Getting unauthorized access for JS Report .Net Core issue in remote server hosted with IIS

### ISSUE THREAD

**Issue by sureshpoudel** [jsreport/jsreport-dotnet#37]
I am working in .net core 2.1 
have jsreport.aspnetcore(2.0.1)
have jsreport.Binary(2.5.0)
have jsreport.Local(2.1.0)
I am using chromePdf recipe
I do not have issue working in debug mode in VS 2017 and running in localhost using IIS. But when I deploy same published code in the remote machine and try to access it show up without any formatting. 
below is the log

+0      Starting rendering request 1 (user: null)
+0      Rendering anonymous template { recipe: chrome-pdf, engine: none }
+0      Data item not defined for this template.
+0      Resources not defined for this template.
+16     Base url injected: http://test.test.com(renamed actual url)
+16     Rendering engine none
+47     Compiled template not found in the cache, compiling
+47     Executing recipe chrome-pdf
+5125   Converting with chrome HeadlessChrome/76.0.3803.0 using dedicated-process strategy
+7687   Failed to load resource: the server responded with a status of 401 (Unauthorized)
+7687   Failed to load resource: the server responded with a status of 401 (Unauthorized)
+7687   Failed to load resource: the server responded with a status of 401 (Unauthorized)
+7687   Failed to load resource: the server responded with a status of 401 (Unauthorized)
+7780   Failed to load resource: the server responded with a status of 401 (Unauthorized)
+7780   Failed to load resource: the server responded with a status of 401 (Unauthorized)
+7791   Failed to load resource: the server responded with a status of 401 (Unauthorized)
+7791   Failed to load resource: the server responded with a status of 401 (Unauthorized)
+7855   Running chrome with params {"margin":{},"printBackground":true}
+8198   Skipping storing report.
+8198   Rendering request 1 finished in 8198 ms

**Comment by tietoTomas** [comment]
I have the same problem but cannot solve it with inline. Is there any way to configure the path?

**Comment by pofider** [comment]
A lot has changed in the jsreport v3 sdk, please test it there and come back if you have still troubles.
