### ISSUE TITLE
Error rendering report: rendering has finished with errors:Error during rendering report: Recipe must be specified #343

### ISSUE THREAD

**Issue by CoolM1234** [jsreport/jsreport-dotnet#4]
Issue: https://github.com/jsreport/jsreport/issues/343

Thanks for reply~ :smile: 

This is my sample repository  ( https://github.com/CoolM1234/MVC5AJ1JSreport ).

FilterConfig
----------------------
1) I have manually create a FilterConfig.cs (https://github.com/CoolM1234/MVC5AJ1JSreport/blob/master/MVC5AJ1%20-%20Template/src/MVC5AJ1.Web/App_Start/Filter/FilterConfig.cs#L12)

2) Add a Global Filter at (https://github.com/CoolM1234/MVC5AJ1JSreport/blob/86a14d94c4dc287b3862a4b4695795290b265496/MVC5AJ1%20-%20Template/src/MVC5AJ1.Web/App_Start/MVC5AJ1WebModule.cs#L84)

Controller
------------------------
1) Report Controller  (https://github.com/CoolM1234/MVC5AJ1JSreport/blob/86a14d94c4dc287b3862a4b4695795290b265496/MVC5AJ1%20-%20Template/src/MVC5AJ1.Web/Controllers/ReportController.cs#L20)

View
-------------------------
1) Index.cshtml -- create a button
(https://github.com/CoolM1234/MVC5AJ1JSreport/blob/86a14d94c4dc287b3862a4b4695795290b265496/MVC5AJ1%20-%20Template/src/MVC5AJ1.Web/Views/Report/Index.cshtml#L8)

2) Invoice.cshtml ----- my report design
(https://github.com/CoolM1234/MVC5AJ1JSreport/blob/master/MVC5AJ1%20-%20Template/src/MVC5AJ1.Web/Views/Report/Invoice.cshtml)

Have I missing any step?

**Comment by CoolM1234** [comment]
The dependencies of .Net Framework must using 4.6 v??or can above?? Becuz my template framework is using .Net framework 4.6.1 v.

**Comment by pofider** [comment]
The version shouldn't be an issue.

I'm trying your repository but app doesn't start up. I pre-created a DB but then I get error "No language defined in this application. ". Could you please extract the issue into the smallest app I can look at? Or give me some steps how to start it up.

**Comment by CoolM1234** [comment]
Thank for your kind attention :smile: 

1) Must connecting to your db first
------------------------
1)Web.config----- At "connectionString" change your db
(https://github.com/CoolM1234/MVC5AJ1JSreport/blob/86a14d94c4dc287b3862a4b4695795290b265496/MVC5AJ1%20-%20Template/src/MVC5AJ1.Web/Web.config#L59)
---------------------------

2) Then, open 'package Manage Console'. 
--------------------------
3) Next, 'Default project' choose to "MVC5AJ1.EntityFramework". 
-------------------------
4) PM> update-database

**Comment by pofider** [comment]
Thank you. I was missing the 4th step.

I found out that you call another action in your layout which clears up the already specified recipe. This was our bug which I just fixed.

Please update `jsreport.MVC` to `2.0.1` and try again. It should now work.

Thank you for the bug report. Closing, because I expect it to be fixed now.

**Comment by CoolM1234** [comment]
:+1: :smiley: Now, the report is working now .
Thanks you very much :smile:
