### ISSUE TITLE
Reporting Configuration

### ISSUE THREAD

**Issue by Smoovsky** [jsreport/jsreport-dotnet#40]
Hi there,

I got a few questions with regard to the reporting configuration of .NET SDK.

When it comes to folder/path configuration, the Configuration class has:
1. TempDirectory - folder to store binary(jsreport.exe, chromium, etc.)
2. BaseUrl/ BaseUrlAsWorkingDirectory - not sure what is this for

Also, the reporting itself has a "RunInDirectory" to be called during initializing, to discover preloaded templates.

It's a bit confusing, mainly about BaseUrl/ BaseUrlAsWorkingDirectory in the Configuration object.

Thanks.

**Comment by pofider** [comment]
Yes, it is a bit confusing, we need to update some .net docs to reflect it.

**TempDirectory**  - where the binaries are extracted to and also where we store temporary files before html->pdf conversion and so on

**RunInDirectory** - is working directory where jsreport.exe gets started, this is a place where jsreport searches by default for config file, license, templates data directory.... 

**BaseUrl** - is used by [base](https://jsreport.net/learn/base) jsreport extension. This extension automatically injects into html [base tag](https://www.w3schools.com/tags/tag_base.asp). This is helpful if you relatively reference css/js in your html and you want it to be relative to the particular location on the disk or particular web url
