### ISSUE TITLE
jsreport.Client.JsReportException in mscorlib.dll

### ISSUE THREAD

**Issue by LanTenDragon** [jsreport/jsreport-dotnet#41]
I am trying to get jsreport up and running on my ASP.NETStandard project. I followed the steps in https://jsreport.net/learn/dotnet-client, the most basic one where I start a ReportingService first, then use C# to send real data. This is my sample code.

I would like to perform PDF download when the user presses a button, which is ``Button1_Click`` in the code below.

```
public partial class WebForm1 : System.Web.UI.Page
{
	ReportingService rs2;

    protected void Page_Load(object sender, EventArgs e)
    {
    	rs2 = new ReportingService("http://localhost:5488");
	}

	protected async void Button1_Click(object sender, EventArgs e)
    {
        var report3 = await rs2.RenderByNameAsync("Invoice", new
        {
        	Number = "123",
            Seller = new CompanyModel()
            {
          		Name = "Next Step Webs, Inc.",
                Road = "12345 Sunny Road",
                Country = "Sunnyville, TX 12345"
            },
			//More data here
       	});
	}
}
```

When I preess the button, `Exception thrown: 'jsreport.Client.JsReportException' in mscorlib.dll` appears. Being on Visual Studio Community, how should I get the full stack trace? 

Note that the ``localhost:5488`` jsreport studio page works perfectly fine.

**Comment by pofider** [comment]
Could you share this sample project somewhere on github?
I don't think the stacktrace could get just lost on our side.

**Comment by LanTenDragon** [comment]
Here's my sample project
https://github.com/LanTenDragon/sample-jsreport-.NET

# Few things to note:
First of all, I surrounded all code with ``try catch`` for all exceptions and that might be why the stack trace went missing. I removed the catch in my sample project.

The circumstances of my problem has changed a lot. I swear that yesterday night initialising a ``new ReportingService();`` worked fine, until the next day, where it keeps silently failing. Now I always hit `System.Net.Http.HttpRequestException` so I cant proceed and confirm that the `try catch` indeed has been eating the stack trace.

**Comment by LanTenDragon** [comment]
Closing this issue as I managed to circumvent this by going for the `jsreport on another console app` road.
