### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by suhaimim** [jsreport/jsreport-dotnet#43]
Dear Developer,
I am having this error message during executing the PDF.
``An unhandled exception occurred while processing the request.
JsReportBinaryException: Error rendering report: instance has been daemonized and initialized successfully (pid: 13380)rendering has finished with errors:A critical error occurred while trying to execute the render command (2). Error while executing request to remote server: Unknown error, status code 504 (1). caused by error (2):-> stackError: at onCriticalError (D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:302:19) at exports.handler (D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:256:14) at process._tickCallback (internal/process/next_tick.js:68:7)caused by error (1):-> meta = {"response":{"statusCode":504,"headers":{"connection":"close","content-type":"text/html","cache-control":"no-cache","x-frame-options":"SAMEORIGIN","x-xss-protection":"1; mode=block","x-content-type-options":"nosniff","content-security-policy":"frame-ancestors","content-length":"1624"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"localhost:5488","port":"5488","hostname":"localhost","hash":null,"search":null,"query":null,"pathname":"/api/report","path":"/api/report","href":"http://localhost:5488/api/report"},"method":"POST","headers":{"Content-Type":"application/json","content-length":25296}}}}-> stackError: at render.responseStream.on.responseToBuffer (D:\snapshot\jsreport\node_modules\jsreport-client\lib\client.js:0:0) at concat (D:\snapshot\jsreport\node_modules\jsreport-client\lib\client.js:0:0) at ConcatStream.<anonymous> (D:\snapshot\jsreport\node_modules\concat-stream\index.js:36:43) at ConcatStream.emit (events.js:194:15) at finishMaybe (D:\snapshot\jsreport\node_modules\readable-stream\lib\_stream_writable.js:630:14) at afterWrite (D:\snapshot\jsreport\node_modules\readable-stream\lib\_stream_writable.js:492:3) at process._tickCallback (internal/process/next_tick.js:63:19)Parsing Error stack: SyntaxError: Unexpected token < in JSON at position 0 at JSON.parse (<anonymous>) at render.responseStream.on.responseToBuffer (D:\snapshot\jsreport\node_modules\jsreport-client\lib\client.js:0:0) at concat (D:\snapshot\jsreport\node_modules\jsreport-client\lib\client.js:0:0) at ConcatStream.<anonymous> (D:\snapshot\jsreport\node_modules\concat-stream\index.js:36:43) at ConcatStream.emit (events.js:194:15) at finishMaybe (D:\snapshot\jsreport\node_modules\readable-stream\lib\_stream_writable.js:630:14) at afterWrite (D:\snapshot\jsreport\node_modules\readable-stream\lib\_stream_writable.js:492:3) at process._tickCallback (internal/process/next_tick.js:63:19)
jsreport.Local.Internal.LocalUtilityReportingService.RenderAsync(string requestString, CancellationToken ct)``

**Comment by pofider** [comment]
Please try to use pre-release nuget jsreport.Binary@2.6.2-beta2.
Do you see the same problem there?

**Comment by suhaimim** [comment]
All those 3 issues raised are using the jsreport.Binary@2.6.2-beta2

**Comment by pofider** [comment]
Thank you. The jsreport.Local/binary by default spans another process with jsreport.exe and communicates with it through http/localhost. It seems you have a more complex environment and this communication is failing.

Please try to call this. It should disable internal http communication and just start and end jsreport.exe every time you render. It is less performing, but it anyway doesn't matter for bigger pdf processes.

```
...
.AsUtility()
.KeepAlive(false)
```

**Comment by suhaimim** [comment]
Seems the issues is remain there even after add .KeepAlive(false)


**An unhandled exception occurred while processing the request.**
```
JsReportBinaryException: Error rendering report: rendering has finished with errors:A critical error occurred while trying to execute the render command (2). Error while executing request to remote server: Unknown error, status code 504 (1). caused by error (2):-> stackError: at onCriticalError (D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:302:19) at exports.handler (D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:198:14) at process._tickCallback (internal/process/next_tick.js:68:7)caused by error (1):-> meta = {"response":{"statusCode":504,"headers":{"connection":"close","content-type":"text/html","cache-control":"no-cache","x-frame-options":"SAMEORIGIN","x-xss-protection":"1; mode=block","x-content-type-options":"nosniff","content-security-policy":"frame-ancestors","content-length":"1624"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"localhost:5488","port":"5488","hostname":"localhost","hash":null,"search":null,"query":null,"pathname":"/api/report","path":"/api/report","href":"http://localhost:5488/api/report"},"method":"POST","headers":{"Content-Type":"application/json","content-length":25296}}}}-> stackError: at render.responseStream.on.responseToBuffer (D:\snapshot\jsreport\node_modules\jsreport-client\lib\client.js:0:0) at concat (D:\snapshot\jsreport\node_modules\jsreport-client\lib\client.js:0:0) at ConcatStream.<anonymous> (D:\snapshot\jsreport\node_modules\concat-stream\index.js:36:43) at ConcatStream.emit (events.js:194:15) at finishMaybe (D:\snapshot\jsreport\node_modules\readable-stream\lib\_stream_writable.js:630:14) at endWritable (D:\snapshot\jsreport\node_modules\readable-stream\lib\_stream_writable.js:638:3) at ConcatStream.Writable.end (D:\snapshot\jsreport\node_modules\readable-stream\lib\_stream_writable.js:594:41) at IncomingMessage.onend (_stream_readable.js:651:10) at Object.onceWrapper (events.js:277:13) at IncomingMessage.emit (events.js:194:15)Parsing Error stack: SyntaxError: Unexpected token < in JSON at position 0 at JSON.parse (<anonymous>) at render.responseStream.on.responseToBuffer (D:\snapshot\jsreport\node_modules\jsreport-client\lib\client.js:0:0) at concat (D:\snapshot\jsreport\node_modules\jsreport-client\lib\client.js:0:0) at ConcatStream.<anonymous> (D:\snapshot\jsreport\node_modules\concat-stream\index.js:36:43) at ConcatStream.emit (events.js:194:15) at finishMaybe (D:\snapshot\jsreport\node_modules\readable-stream\lib\_stream_writable.js:630:14) at endWritable (D:\snapshot\jsreport\node_modules\readable-stream\lib\_stream_writable.js:638:3) at ConcatStream.Writable.end (D:\snapshot\jsreport\node_modules\readable-stream\lib\_stream_writable.js:594:41) at IncomingMessage.onend (_stream_readable.js:651:10) at Object.onceWrapper (events.js:277:13)
jsreport.Local.Internal.LocalUtilityReportingService.RenderAsync(string requestString, CancellationToken ct)

```

**Comment by pofider** [comment]
It seems it is using an binary orphan. 
Please try to kill nodejs processes,  use `KillRunningJsReportProcesses` or just reboot.

```
....
.KillRunningJsReportProcesses()
.UseBinary(JsReportBinary.GetBinary())
```

**Comment by suhaimim** [comment]
Yes, you solve the issues. Thank you Sir.

**Comment by suhaimim** [comment]
Hi, 
Out of sudden, this error appeared.
Original code unchanged.

`            services.AddJsReport(new LocalReporting()
                    .KillRunningJsReportProcesses()
                    .UseBinary(JsReportBinary.GetBinary())
                    .AsUtility()
                    .KeepAlive(false)
                    .Create()
                );
`

JsReportBinaryException: Error rendering report: starting rendering process..rendering has finished with errors:A critical error occurred while trying to execute the render command (2). spawn UNKNOWN (1). caused by error (2):-> stackError: at onCriticalError (D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:302:19) at exports.handler (D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:298:12)caused by error (1):-> meta = {"errno":"UNKNOWN","code":"UNKNOWN","syscall":"spawn","logged":true}-> stackError: at ChildProcess.spawn (internal/child_process.js:366:11) at Object.spawn (child_process.js:538:9) at Object.childProcess.spawn (pkg/prelude/bootstrap.js:1433:27) at Launcher.launch (D:\snapshot\jsreport\node_modules\puppeteer\lib\Launcher.js:126:40)

**Comment by suhaimim** [comment]
Now, 500 error page only appear. Nothing change on pdf setting.

**Comment by pofider** [comment]
Still the same error message?
The error the most likely signals jsreport wants to execute chrome for pdf conversion but it got blocked (maybe by antivirus) or deleted. By default, jsreport uses os temp directory for storing chrome binary.

Perhaps you can use your own temp directory you have full control over. Maybe something is cleaning your os temp.
```
.UseBinary(JsReportBinary.GetBinary()) 
.TempDirectory(...)
```

**Comment by suhaimim** [comment]
This page isn’t workinglocalhost is currently unable to handle this request.
HTTP ERROR 500

**Comment by suhaimim** [comment]
jsreport.AspNetCore(2.0.2)
jsreport.Binary(2.6.2-beta2)
jsreport.Client(3.0.1)
jsreport.Local(2.2.1)
jsreport.Shared(2.1.0)
jsreport.Types(2.6.1)

**Comment by suhaimim** [comment]
`            HttpContext.JsReportFeature()
                .Configure((r) =>
                r.Template = new Template
                {
                    Engine = Engine.Handlebars,
                    Recipe = Recipe.ChromePdf,
                    Chrome = new Chrome
                    {
                        DisplayHeaderFooter = false,
                        MediaType = MediaType.Print,
                        MarginTop = "1cm",
                        MarginLeft = "1mm",
                        MarginBottom = "1cm",
                        MarginRight = "1mm",
                    },
                });`

**Comment by suhaimim** [comment]
All firewall and antivirus has disabled.

**Comment by pofider** [comment]
Please provide the full error message and stack trace.

**Comment by suhaimim** [comment]
Unfortunately, I cant reproduce the error earlier. 
Now, only 500 error screen.
So far no changes been made. Suddenly.

**Comment by pofider** [comment]
The error doesn't just disappear. You have likely some kind of asp.net core or web server feature that intentionally hides the error in production. You need to disable it or have some logs that get the errors.

This is, for example, a common line in the asp.net core apps that hides the errors behind 500 error pages.

```
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
```

**Comment by suhaimim** [comment]
Not sure what cause the error.
The error behid the page remain enabled.

However the problem just resolved by clearing the jsreport temp folder that created inside %UserHomePath%\AppData\ Local\Temp\jsreport 

Thank you for your immediate response that provide lots of clues and solutions.

**Comment by muralis2210** [comment]
Hi , similar error. Please help. 
JsReportBinaryException: Error rendering report: A critical error occurred while trying to execute the render command (2). An error occurred while trying to start daemonized process: An error has occurred when trying to initialize jsreport, seems like there is already a server running in port: 5488 (1). caused by error (2):-> stackError: at onCriticalError (D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:302:19) at D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:256:14caused by error (1):-> meta = {"code":"EADDRINUSE"}-> stackError: An error has occurred when trying to initialize jsreport, seems like there is already a server running in port: 5488 at Object.<anonymous> (D:\snapshot\jsreport\node_modules\jsreport-cli\lib\keepAliveProcess.js:158:27) at Object.listener (D:\snapshot\jsreport\node_modules\eventemitter2\lib\eventemitter2.js:251:10) at Object.emit (D:\snapshot\jsreport\node_modules\eventemitter2\lib\eventemitter2.js:339:22) at Object._onData (D:\snapshot\jsreport\node_modules\nssocket\lib\nssocket.js:454:8) at Lazy.<anonymous> (D:\snapshot\jsreport\node_modules\lazy\lazy.js:91:13) at Lazy.<anonymous> (D:\snapshot\jsreport\node_modules\lazy\lazy.js:73:19) at Lazy.emit (events.js:311:20) at Lazy.<anonymous> (D:\snapshot\jsreport\node_modules\lazy\lazy.js:74:22) at Lazy.emit (events.js:311:20) at yieldTo (D:\snapshot\jsreport\node_modules\lazy\lazy.js:181:18)Remote Instance Error: Error: at D:\snapshot\jsreport\node_modules\jsreport-cli\lib\instanceHandler.js:31:29Remote Instance Error: Error: at Server.setupListenHandle [as _listen2] (net.js:1309:16) at listenInCluster (net.js:1357:12) at Server.listen (net.js:1445:7) at D:\snapshot\jsreport\node_modules\jsreport-express\lib\reporter.express.js:23:12 at Promise._execute (D:\snapshot\jsreport\node_modules\bluebird\js\release\debuggability.js:313:9) at Promise._resolveFromExecutor (D:\snapshot\jsreport\node_modules\bluebird\js\release\promise.js:483:18) at new Promise (D:\snapshot\jsreport\node_modules\bluebird\js\release\promise.js:79:10) at startAsync (D:\snapshot\jsreport\node_modules\jsreport-express\lib\reporter.express.js:17:10) at D:\snapshot\jsreport\node_modules\jsreport-express\lib\reporter.express.js:51:14 at Object.start (D:\snapshot\jsreport\node_modules\jsreport-express\lib\reporter.express.js:125:13) at Object.<anonymous> (D:\snapshot\jsreport\node_modules\jsreport-express\lib\reporter.express.js:317:30)
jsreport.Local.Internal.LocalUtilityReportingService.RenderAsync(string requestString, CancellationToken ct)

**Comment by pofider** [comment]
@muralis2210 Something is blocking port 5488. Maybe another jsreport instance? In that case, configure jsreport to use a different port. Or just reboot the system, maybe there is an orphan process blocking it.
