### ISSUE TITLE
Huge performance difference between "AsWebServer" and "AsUtility"

### ISSUE THREAD

**Issue by Smoovsky** [jsreport/jsreport-dotnet#44]
The doc suggests that "AsUtility" is generally recommended under the production environment, but we are looking at around 10x performance difference, especially rendering PDFs.

**Comment by pofider** [comment]
How long does the pdf rendering take for you?
Do you compare the second rendering request times?

You can use the AsWebServer in your production environment,
The problem is that there is no logic in place of what to do if the jsreport.exe process dies.
In the case of Asutility such logic is in place.

**Comment by Smoovsky** [comment]
> How long does the pdf rendering take for you?
> Do you compare the second rendering request times?
> 
> You can use the AsWebServer in your production environment,
> The problem is that there is no logic in place of what to do if the jsreport.exe process dies.
> In the case of Asutility such logic is in place.

Hi there,
For pdf rendering, I was looking at around 100ms when AsWebServer, but 1000ms-1500ms when AsUtility even when the process is already cooked up.

I have encapsulated a logic as it will kill the JsReport process (along with any processes running from that folder, e.g. chrome.exe) and then try to restart it if the rendering failed. Does that mean it is safe to use AsWebServer in production?

Also, are may I know if you are planning to fix the performance issue as mentioned in the docs, when will be the release roughly?

Thanks.

**Comment by pofider** [comment]
The performance with utility should be much better with 2.7.0 and it gets very close to the as web server option. I will share some numbers when we are three. Hopefully in one or two weeks.

If the automatic restarts work for you, then great, use it.

**Comment by Smoovsky** [comment]
> The performance with utility should be much better with 2.7.0 and it gets very close to the as web server option. I will share some numbers when we are three. Hopefully in one or two weeks.
> 
> If the automatic restarts work for you, then great, use it.

Thanks for the info, will be looking forward to the release.
