### ISSUE TITLE
How can i use pdf utils in jsreport dotnet ?

### ISSUE THREAD

**Issue by cdespinosaagmx** [jsreport/jsreport-dotnet#47]
I want to know if i can use pdf utils only using the jsreport dotnet engine using Binary and Local nuget, and if i need some initialization code in c# that i have to implement to use pdf utils

**Comment by pofider** [comment]
Here is an example
https://jsreport.net/learn/dotnet-client#pdf-utils

However, I recommend thinking through if it isn't better to run a full standalone jsreport service with stored and configured templates.

**Comment by cdespinosaagmx** [comment]
Well i'm developing an Report Editor using a merge of different tools, in this case i only need jsreport html to pdf engine, and some tools from jsreport... I'm trying to do an Complete Report Editor like Crystal Reports but improved using grapesjs, blockly, ckeditor, jsreport, pivottable.js and chart.js... is a little difficult to adapt the tools in one but i'm almost done to complete a first version of this Tool.

**Comment by pofider** [comment]
Ok. Thank you for the details... I would be definitely interested in checking it out when you have some prototype and maybe give you comments if you would be interested.

**Comment by cdespinosaagmx** [comment]
Okay, i will let u know when i finish it, i only have 1 month working on it i'm trying to improve and integrate some operations yet, but thanks for your help.

**Comment by cdespinosaagmx** [comment]
Jah, is there any chat to talk with you instead of issues? i have one problem but i don't want to create another issue for this little problem

**Comment by pofider** [comment]
We are on [gitter](https://gitter.im/jsreport/jsreport?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) usually. Or [forum](https://forum.jsreport.net/) is preferred.
