### ISSUE TITLE
Remote URL Download

### ISSUE THREAD

**Issue by mike-dube** [jsreport/jsreport-dotnet#54]
Hello,

I'm looking to replace AthenaPDF in our project. Can we use JSReport-NetCore to fetch a remote URL?

I would create a microservice-based on that to handle pdf generation to bytes.

**Comment by pofider** [comment]
Do you mean convert html to pdf from a remote URL?
https://jsreport.net/learn/chrome-pdf#printing-existing-web-pages

The request in c# can look something like this
```csharp
new RenderRequest { 
   Template  = new {
        Recipe = Recipe.ChromePdf,
        Engine = Engine.None,
        Content = 'placeholder',
        ....
        Chrome = new Chrome {
           Url = "https://xxxxxxx"
        }
   }
}
```
