### ISSUE TITLE
Instance has been daemonized and initialized successfully (pid: 12644)rendering has finished with errors

### ISSUE THREAD

**Issue by RodrigoMorellato** [jsreport/jsreport-dotnet#56]
Hello.
I have been using the jsreport without problems, but the application has started to have the follow exception in release server (test server no problem). 

Please, could you help me? Any help would be appreciate.

"Error rendering report: instance has been daemonized and initialized successfully (pid: 12644)rendering has finished with errors:A critical error occurred while trying to execute the render command (2). spawn UNKNOWN (1). caused by error (2):-> stackError:    at onCriticalError (D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:302:19)    at D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:256:14    at processTicksAndRejections (internal/process/task_queues.js:97:5)caused by error (1):-> stackError:    at Client.render (D:\snapshot\jsreport\node_modules\jsreport-client\lib\client.js)    at processTicksAndRejections (internal/process/task_queues.js:97:5)    at async startRender (D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:319:24)    at async D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:226:22    at async Commander.executeCommand (D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commander.js:242:22)Remote stack: Error:    at ChildProcess.spawn (internal/child_process.js:407:11)    at Object.spawn (child_process.js:548:9)    at Object.childProcess.spawn (pkg/prelude/bootstrap.js:1496:27)    at Launcher.launch (D:\snapshot\jsreport\node_modules\puppeteer\lib\Launcher.js:132:40)    at async getBrowser (D:\snapshot\jsreport\node_modules\jsreport-chrome-pdf\lib\dedicatedProcessStrategy.js:13:21)    at async D:\snapshot\jsreport\node_modules\jsreport-chrome-pdf\lib\conversion.js:4:19    at async execute (D:\snapshot\jsreport\node_modules\jsreport-chrome-pdf\lib\dedicatedProcessStrategy.js:10:22)    at async Object.execute (D:\snapshot\jsreport\node_modules\jsreport-chrome-pdf\lib\chrome.js:69:20)    at async D:\snapshot\jsreport\node_modules\jsreport-core\lib\render\render.js:149:5"

![Captura de tela 2021-04-06 095219](https://user-images.githubusercontent.com/35920145/113685134-d5823e00-96bd-11eb-8292-83ae2da84fcd.png)

**Comment by pofider** [comment]
It seems it has problems with launching chrome.
Please try the following:
- stop jsreport daemon processes by killing "node.exe" processes.
- remove jsreport temp files, its typically here `c:\Users\xxx\AppData\Local\Temp\jsreport\`,
- try to render again

**Comment by RodrigoMorellato** [comment]
Wonderful... it worked.

Many thanks for your help and fast reply!!!

**Comment by Farukest** [comment]
it worked after killing "node.exe" from task manager and then removing temp files. tx

**Comment by antmeehan** [comment]
@pofider We just hit this issue in Prod (and thankfully I found your fix!). Any ideas on a cause? Or just random chrome issue?

**Comment by pofider** [comment]
Maybe something is partially corrupting the temp directory and it would be better to use another safe dir.
You can try to use another safe dir if the problem reoccurs. 
https://jsreport.net/learn/dotnet-local#temp-files

It could help me to have some insights if you share the jsreport temp folder content with me when the problem occurs.

**Comment by antmeehan** [comment]
Thanks for responding. I had a look at the copy of the temp folder that was failing, and the only recently updated files were in the `autocleanup` folder (a bunch of html and json files) and then the `debug.log` file in `compile\jsreport-2.9.0-SJEB3Pyev\chrome`.

The `debug.log` file had some entries (about PruneCrashReportDatabase) but they had been occurring for over a year (and the service has been running fine until just last week).

If we hit the issue again, perhaps we'll periodically clean up the temp folder.

**Comment by eiz-dmis** [comment]
> It seems it has problems with launching chrome. Please try the following:
> 
> * stop jsreport daemon processes by killing "node.exe" processes.
> * remove jsreport temp files, its typically here `c:\Users\xxx\AppData\Local\Temp\jsreport\`,
> * try to render again

Worked like a charm. Thank you.
