### ISSUE TITLE
Error rendering report: instance has been daemonized

### ISSUE THREAD

**Issue by nfleuret** [jsreport/jsreport-dotnet#57]
Hello,
I am using jsreport as a pdf generator in a ASP .Net 5 Web project.
Last time I checked the project (two weeks ago) all was working fine and I am the only developer working on it.
The only change that comes to my mind is a visual studio update but I do not think it could be linked to the current issue.

I followed the example provided in the demo and here is my structure:
I have added the following Nuget packages:
jsreport.AspNetCore (2.1.0)
jsreport.Binary (2.11.0)
jsreport.Local (2.3.1)

Within my Startup.cs file, I have the following statement:
```
services.AddJsReport(new LocalReporting().UseBinary(JsReportBinary.GetBinary()).AsUtility().Create());
```

Then in a controller, I have:
```
[MiddlewareFilter(typeof(JsReportPipeline))]
public IActionResult Test()
{
    HttpContext.JsReportFeature()
       .Recipe(Recipe.ChromePdf);
    return View();
}
```

And here is the view:
```
@{ Layout = null; }

<!DOCTYPE html>
<html>
<head>
</head>
<body>
    <p>This is a test</p>
</body>
</html>
```

This is indeed a simplified version of my controller and view but it gives me the same error than with my previous controller/view and I did this testing to focus on the issue.

**This is the error I get:**
JsReportBinaryException: Error rendering report: rendering has finished with errors:A critical error occurred while trying to execute the render command (2). spawn UNKNOWN (1). caused by error (2):-> stackError: at onCriticalError (D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:302:19) at D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:201:16 at processTicksAndRejections (internal/process/task_queues.js:97:5)caused by error (1):-> stackError: at Client.render (D:\snapshot\jsreport\node_modules\jsreport-client\lib\client.js) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async startRender (D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:319:24) at async D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:186:24 at async Commander.executeCommand (D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commander.js:242:22)Remote stack: Error: at ChildProcess.spawn (internal/child_process.js:407:11) at Object.spawn (child_process.js:548:9) at Object.childProcess.spawn (pkg/prelude/bootstrap.js:1496:27) at Launcher.launch (D:\snapshot\jsreport\node_modules\puppeteer\lib\Launcher.js:132:40) at async getBrowser (D:\snapshot\jsreport\node_modules\jsreport-chrome-pdf\lib\dedicatedProcessStrategy.js:13:21) at async D:\snapshot\jsreport\node_modules\jsreport-chrome-pdf\lib\conversion.js:4:19 at async execute (D:\snapshot\jsreport\node_modules\jsreport-chrome-pdf\lib\dedicatedProcessStrategy.js:10:22) at async Object.execute (D:\snapshot\jsreport\node_modules\jsreport-chrome-pdf\lib\chrome.js:68:20) at async D:\snapshot\jsreport\node_modules\jsreport-core\lib\render\render.js:150:5

I do not know if there is a link between "D:\snapshot\jsreport\..." and my machine but there is no D: drive on my laptop.

Thanks for any help you could provide.

**Comment by pofider** [comment]
Please kill all running node.js processes, delete folder `c:\Users\xxx\AppData\Local\Temp\jsreport\` and start again.

**Comment by nfleuret** [comment]
Thanks for your quick and efficient advice: this is indeed all it needed to work again.
I very much appreciate your work and support.
