### ISSUE TITLE
Linux docker is giving error.

### ISSUE THREAD

**Issue by vidya091209** [jsreport/jsreport-dotnet#58]
This is my code

     var report = await _jsReportMVCService.RenderAsync(new RenderRequest()
                {
                    Template = new Template
                    {
                        Content = "<h1>Hello world</h1>",
                        Engine = Engine.None,
                        Recipe = Recipe.ChromePdf
                    }
                });
Startup
   services.AddJsReport(new LocalReporting()
                .UseBinary(RuntimeInformation.IsOSPlatform(OSPlatform.Linux) ? jsreport.Binary.Linux.JsReportBinary.GetBinary() :
                JsReportBinary.GetBinary())
                  .KillRunningJsReportProcesses()
                         .Configure((cfg) =>
                         {
                                    // explicitly set port, because azure web app sets environment variable PORT
                                    // which is used also by jsreport
                                    cfg.HttpPort = 1000;
                             return cfg;
                         })
                .AsUtility()
                .Create());

**Note: This works on windows machine but fails on linux docker.**

Error rendering report: instance has been daemonized and initialized successfully (pid: 540)rendering has finished with errors:A critical error occurred while trying to execute the render command (2). Failed to launch chrome!/tmp/jsreport/compile/jsreport-2.11.0-BkQPrWToP/chrome/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directoryTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md (1). caused by error (2):-> stackError:    at onCriticalError (/snapshot/jsreport/node_modules/jsreport-cli/lib/commands/render.js:302:19)    at /snapshot/jsreport/node_modules/jsreport-cli/lib/commands/render.js:256:14    at processTicksAndRejections (internal/process/task_queues.js:97:5)caused by error (1):-> stackError: Failed to launch chrome!/tmp/jsreport/compile/jsreport-2.11.0-BkQPrWToP/chrome/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directoryTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md    at Client.render (/snapshot/jsreport/node_modules/jsreport-client/lib/client.js)    at processTicksAndRejections (internal/process/task_queues.js:97:5)    at async startRender (/snapshot/jsreport/node_modules/jsreport-cli/lib/commands/render.js:319:24)    at async /snapshot/jsreport/node_modules/jsreport-cli/lib/commands/render.js:226:22    at async Commander.executeCommand (/snapshot/jsreport/node_modules/jsreport-cli/lib/commander.js:242:22)Remote stack: Error: Failed to launch chrome!/tmp/jsreport/compile/jsreport-2.11.0-BkQPrWToP/chrome/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directoryTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md    at onClose (/snapshot/jsreport/node_modules/puppeteer/lib/Launcher.js:348:14)    at Interface.<anonymous> (/snapshot/jsreport/node_modules/puppeteer/lib/Launcher.js:337:50)    at Interface.emit (events.js:323:22)    at Interface.close (readline.js:409:8)    at Socket.onend (readline.js:187:10)    at Socket.emit (events.js:323:22)    at endReadableNT (_stream_readable.js:1204:12)    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by pofider** [comment]
There are some dependencies you need to install by hand.
Please check out this part of the documentation
https://jsreport.net/learn/dotnet-local#docker

**Comment by vidya091209** [comment]
I am using the same docker file.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
RUN apt-get update

# install chrome with deps, see https://github.com/jsreport/jsreport/blob/master/docker/full/Dockerfile
RUN apt-get install -y --no-install-recommends libgconf-2-4 gnupg git curl wget ca-certificates libgconf-2-4 && \
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
    apt-get update && \  
    apt-get install -y lsb-release google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst libxtst6 libxss1 --no-install-recommends

ENV chrome_launchOptions_executablePath google-chrome-stable
ENV chrome_launchOptions_args --no-sandbox,--disable-dev-shm-usage,--single-process,--no-zygote
WORKDIR /app
EXPOSE 80
EXPOSE 443

**Comment by vidya091209** [comment]
I am running this code in web api. and it works om windows machine.

**Comment by pofider** [comment]
The chrome has changed some dependencies, so an additional line is required. 

This is the full part currently needed
```
# install chrome with deps, see https://github.com/jsreport/jsreport/blob/master/docker/full/Dockerfile
RUN apt-get update && apt-get install -y --no-install-recommends libgconf-2-4 gnupg git curl wget ca-certificates libgconf-2-4 && \
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
    apt-get update && \  
    apt-get install -y lsb-release google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst libxtst6 libxss1 --no-install-recommends

# debian needs this additional install
RUN apt-get install -y libx11-6 libx11-xcb1

ENV chrome_launchOptions_executablePath google-chrome-stable
ENV chrome_launchOptions_args --no-sandbox,--disable-dev-shm-usage,--single-process,--no-zygote
```
