### ISSUE TITLE
Update types for Jsreport v3

### ISSUE THREAD

**Issue by sammeel** [jsreport/jsreport-dotnet#61]
The localization extension in JsReport V3 requires to set language to be set in RenderOptions.Localization.Language
The types are not updated for this and only allow to set the language at RenderOptions.Language (https://jsreport.net/learn/localization)

Please update the Types to match the V3 implementation.

**Comment by pofider** [comment]
Thank you.
It is now added in the jsreport.Types@3.0.0
Please let me know if you miss other types....

**Comment by sammeel** [comment]
@pofider, can you also update the jsreport client nuget package to include the 3.0.0 types package.
