### ISSUE TITLE
Old chromium version

### ISSUE THREAD

**Issue by julianortlieb** [jsreport/jsreport-dotnet#64]
Hi there, 

I create receipts with jsreport on .NET like this:

```CSHARP
var report = await reportService.RenderAsync(new RenderRequest()
{
    Template = new Template
    {
        Content = "<h1>Test/h1>",
        Engine = Engine.None,
        Recipe = Recipe.ChromePdf,
        Chrome = new Chrome()
        {
            Url = url,
            Landscape = true,
            Format = "A4",
            WaitForJS = true, 
            MarginBottom = "2mm",
            MarginLeft = "5mm",
            MarginRight = "5mm",
            MarginTop = "5mm"
        }
    }
});
```

Now the following error occurs in the Javascript of the page that was given as URL to Chrome.
`Uncaught SyntaxError: Unexpected token '?'`
Because of this line of code:
```js
var id = form ?? "standard";
```

The chromium, which is in the temp folder, has the version 79.0.3945.0. The syntax `??` is supported from version 80.
The actual stable version of chromium is 103.0.5060.132.

Is it possible to update the chromium to avoid syntax errors due to using new syntax.

**Comment by pofider** [comment]
We will try to update the `jsreport.Binary` to the v3 which includes the latest chromium soon.
However, until then you better run jsreport as a separate service and just connect to it with `jsreport.Client`.

**Comment by pofider** [comment]
The jsreport v3 binary was released today.
