### ISSUE TITLE
Config object doesn't contain several important settings for JsReport.NET Local.

### ISSUE THREAD

**Issue by foggerty** [jsreport/jsreport-dotnet#66]
JsReport.NET (local) will take the provided `Configuration` class and serialise it into a collection of key/pair values, before passing these to the environment variables of the JsReport instance that it creates.  So the property `Config.Chrome.Strategy` will be turned into the environment variable `chrome_strategy`.

This works fine, but a few of the configuration options listed here are missing.  In particular, `Workers.NumberOfWorkers`, meaning we're unable to set the worker count in code - we set an environment variable at deployment time instead.  This is fine for deployment, but a total pain for local (stress) testing.

It's a trivial fix, so I'm happy to submit a patch if you're accepting pull requests?

**Comment by pofider** [comment]
I apologize... too many repos to watch.

I've added the `workers` config and published new types.
Please don't hesitate to send PRs to the types repo if you find something missing there.
