### ISSUE TITLE
Request: provide PhantomJS 2 for all 3 systems (Win, Unix, OSX)

### ISSUE THREAD

**Issue by Igoreso** [jsreport/jsreport-dotnet#8]
Hi, it is me again :)

The majority of devs in my team use OSX, and since we're using dotnet approach we're kind of blocked because current nuget packages only have PhantomJS 1 in them. Can you please add the version 2?

**Comment by pofider** [comment]
Hi, yes we can make that happen.

However are you aware that phantomjs produces a bit different pdf outputs when it runs on windows vs osx/linux? Mainly the text sizes are different. I'm not sure how you will manage that in your team if your developers have different os.

**Comment by Igoreso** [comment]
Thanks!

Yes, I'm aware of it, I've seen your workaround and I'm working on some adjustments.

Btw, how many recipes are packed in `jsreport.Binary*` packages? I tried a bunch of pdf-related values from `jsreport.Types.Recipe` but only `PhantomPdf` one seem to work, others fail with error that recipe is missing (or something like that). Anyway, this shouldn't be a problem for us once we get our hands on PhantomJS 2, just thought I'd share the issue I stumbled upon.

**Comment by pofider** [comment]
The phantomjs 2 binaries are now published as pre-releases to the nuget.
https://github.com/jsreport/jsreport-dotnet

The jsreport binary includes only the default recipes and extensions. See here
https://jsreport.net/learn/recipes

I will add some notes to docs how to install additional extensions into the project.

**Comment by pofider** [comment]
The docs now also includes article how to install additional recipes and extensions
https://jsreport.net/learn/dotnet-local#custom-extensions

Closing as there is everything needed already done.
